CREATE TABLE Customers (
    CustomerId INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    Email STRING(128) NOT NULL,
    RowVersion BINARY(8) NOT NULL,
    AccountCode STRING NULL,
    FirstName STRING NULL,
    LastName STRING NULL,
    FirstAddress STRING NULL,
    City STRING NULL,
    Country STRING NULL,
    ZipCode STRING NULL,
    Website STRING NULL,
    Active BOOLEAN NOT NULL,
    Enrolled INT NOT NULL,
    PhoneNumber STRING NULL,
    MobileNumber STRING NULL,
    FaxNumber STRING NULL,
    CONSTRAINT PK_Customers PRIMARY KEY (CustomerId),
    UNIQUE (Email)
)
